### ISSUE TITLE
Wheel not spinning and stopping immediately to result

### ISSUE THREAD

**Issue by erwindg** [effectussoftware/react-custom-roulette#165]
wheel is not spinning on edge, brave and chrome, i'm not sure on other browsers but it is not spinning now as of submitting this. its working before but suddenly its not

**Comment by zlatkom1991** [comment]
Same happened for me, couple a days a go, just stop working

**Comment by erwindg** [comment]
> Same happened for me, couple a days a go, just stop working

did you try on any other browsers?

**Comment by zlatkom1991** [comment]
Only works on FF

**Comment by helloWerld** [comment]
Same issue here.

**Comment by mollose** [comment]
Yeah not spinning anymore

**Comment by eduardomolero** [comment]
same here. :/

**Comment by M-tidings** [comment]
yarn add react-custom-roulette@1.3.2 
 
 Downgrading the package work as a temporary fix till the issue is fixed

**Comment by hauphvn** [comment]
> yarn add react-custom-roulette@1.3.2
> 
> Downgrading the package work as a temporary fix till the issue is fixed

It works for me.

**Comment by itsMGA** [comment]
Same here

**Comment by zlatkom1991** [comment]
It's working with 1.4.0 also, and that version is compatible with React 18.0, while 1.3.2 needs to have React 16

**Comment by SaleemMaini** [comment]
I downgrade it to 1.4.0 but it's still not working on chrome, only worked on safari

**Comment by Aditoi2012** [comment]
yea it's not working for me either :/...hopefully it's fixed

**Comment by PierreCrb** [comment]
Same for me, it's not working on Chrome

**Comment by hugues0** [comment]
downgraded to 1.4.0, didnt work, downgraded to 1.3.2 and it worked, hope this helps :)

**Comment by ilbertt** [comment]
> yarn add react-custom-roulette@1.3.2
> 
> Downgrading the package work as a temporary fix till the issue is fixed

Worked for me!

**Comment by billy-the-ape** [comment]
I guess maybe an update to chromium broke it? 1.3.2 is the only fix here too. Seems to work fine in react 18.

**Comment by kenanismaill** [comment]
Same issue happened here 🤦🏻

**Comment by estoylive** [comment]
I had to downgrade to 1.2.0 and it worked for me.

**Comment by billy-the-ape** [comment]
Yes can confirm - 1.3.2 does not work on android chromium browsers (doesn't display at all)

1.2.0 works (but is missing many valuable features such as CursorProps and fontFamily 😢 )

**Comment by Xyzjesus** [comment]
have same issue, latest version doesn't work on android and chrome
